/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`get_identifier_invite`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetIdentifierInviteError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_notify_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchNotifyStatusError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_invite_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostInviteStatusError {
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_notify_member_via_identifier`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostNotifyMemberViaIdentifierError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_store_and_send_identifier_invite`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostStoreAndSendIdentifierInviteError {
    Status400(models::ErrorResponse),
    Status401(models::AuthErrorResponse),
    UnknownValue(serde_json::Value),
}


/// Retrieves the invitation data for a given invite code.
pub async fn get_identifier_invite(configuration: &configuration::Configuration, invite: &str) -> Result<models::GetInviteResponse, Error<GetIdentifierInviteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_invite = invite;

    let uri_str = format!("{}/members/invite/{invite}", configuration.base_path, invite=crate::apis::urlencode(p_path_invite));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetInviteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetInviteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetIdentifierInviteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates the status of a notification identifier.
pub async fn patch_notify_status(configuration: &configuration::Configuration, update_notification_status_request_body: Option<models::UpdateNotificationStatusRequestBody>) -> Result<models::CreateIdentifierResponse, Error<PatchNotifyStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_update_notification_status_request_body = update_notification_status_request_body;

    let uri_str = format!("{}/members/notify/status", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_update_notification_status_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateIdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateIdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchNotifyStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Checks the status of an invitation without modifying it.
pub async fn post_invite_status(configuration: &configuration::Configuration, invite_status_request_body: Option<models::InviteStatusRequestBody>) -> Result<models::InviteStatusResponse, Error<PostInviteStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_invite_status_request_body = invite_status_request_body;

    let uri_str = format!("{}/members/invite/status", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_invite_status_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InviteStatusResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InviteStatusResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostInviteStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Sends a notification (email or SMS) to a member using their identifier for authentication.
pub async fn post_notify_member_via_identifier(configuration: &configuration::Configuration, notify_member_request_body: Option<models::NotifyMemberRequestBody>) -> Result<models::CreateIdentifierResponse, Error<PostNotifyMemberViaIdentifierError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_notify_member_request_body = notify_member_request_body;

    let uri_str = format!("{}/members/notify", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_notify_member_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreateIdentifierResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreateIdentifierResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostNotifyMemberViaIdentifierError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Stores an invitation code and sends an invitation to the member via their identifier.
pub async fn post_store_and_send_identifier_invite(configuration: &configuration::Configuration, invite_request_body: Option<models::InviteRequestBody>) -> Result<models::GetInviteResponse, Error<PostStoreAndSendIdentifierInviteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_invite_request_body = invite_request_body;

    let uri_str = format!("{}/members/invite", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.oauth_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_invite_request_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetInviteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetInviteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostStoreAndSendIdentifierInviteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

