/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateIdentifierResponse : Response when creating an identifier
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIdentifierResponse {
    /// Whether the operation succeeded
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    /// The newly created identifier UUID
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<uuid::Uuid>,
}

impl CreateIdentifierResponse {
    /// Response when creating an identifier
    pub fn new() -> CreateIdentifierResponse {
        CreateIdentifierResponse {
            success: None,
            identifier: None,
        }
    }
}

