/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FtcIdentifyUrlResponse : Response containing the FTC or Identify URL and QR code
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FtcIdentifyUrlResponse {
    /// The one-time URL for FTC or identification
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// QR code representation of the URL
    #[serde(rename = "qr", skip_serializing_if = "Option::is_none")]
    pub qr: Option<String>,
}

impl FtcIdentifyUrlResponse {
    /// Response containing the FTC or Identify URL and QR code
    pub fn new() -> FtcIdentifyUrlResponse {
        FtcIdentifyUrlResponse {
            url: None,
            qr: None,
        }
    }
}

