/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FtcSetupRequestBody : Request body for First Time Connection setup
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FtcSetupRequestBody {
    /// The connection NID
    #[serde(rename = "connection_nid")]
    pub connection_nid: String,
    /// The hashed connection token
    #[serde(rename = "connection_token_hash")]
    pub connection_token_hash: String,
    /// The URL to return to after connection
    #[serde(rename = "return_to")]
    pub return_to: String,
    /// The MydexID if already known (required if version > 1)
    #[serde(rename = "mydexid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mydexid: Option<Option<String>>,
    /// The connection version (default 1, must be >= 1)
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    /// A unique ID representing the member in the subscriber's backend
    #[serde(rename = "linking_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub linking_token: Option<Option<String>>,
}

impl FtcSetupRequestBody {
    /// Request body for First Time Connection setup
    pub fn new(connection_nid: String, connection_token_hash: String, return_to: String) -> FtcSetupRequestBody {
        FtcSetupRequestBody {
            connection_nid,
            connection_token_hash,
            return_to,
            mydexid: None,
            version: None,
            linking_token: None,
        }
    }
}

