/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInviteResponse : Response when getting an invitation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInviteResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    /// The invitation URL code
    #[serde(rename = "invite_url_code", skip_serializing_if = "Option::is_none")]
    pub invite_url_code: Option<String>,
    /// The parent identifier UUID
    #[serde(rename = "parent_uuid", skip_serializing_if = "Option::is_none")]
    pub parent_uuid: Option<uuid::Uuid>,
    /// The application URL
    #[serde(rename = "app_url", skip_serializing_if = "Option::is_none")]
    pub app_url: Option<String>,
    /// The OAuth2 client ID
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// The connection NID
    #[serde(rename = "con_nid", skip_serializing_if = "Option::is_none")]
    pub con_nid: Option<String>,
    /// The organization ID
    #[serde(rename = "org_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub org_id: Option<Option<String>>,
    /// The project ID
    #[serde(rename = "project_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<Option<String>>,
    /// The item ID
    #[serde(rename = "item_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item_id: Option<Option<String>>,
    /// The type of invitation
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl GetInviteResponse {
    /// Response when getting an invitation
    pub fn new() -> GetInviteResponse {
        GetInviteResponse {
            success: None,
            invite_url_code: None,
            parent_uuid: None,
            app_url: None,
            client_id: None,
            con_nid: None,
            org_id: None,
            project_id: None,
            item_id: None,
            r#type: None,
        }
    }
}

