/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetIdentifiersResponse : Response when getting all identifiers for a member
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIdentifiersResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    #[serde(rename = "identifiers", skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<Vec<models::IdentifierObject>>,
}

impl GetIdentifiersResponse {
    /// Response when getting all identifiers for a member
    pub fn new() -> GetIdentifiersResponse {
        GetIdentifiersResponse {
            success: None,
            identifiers: None,
        }
    }
}

