/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdentifyRequestBody : Request body for identification URL setup
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifyRequestBody {
    /// The connection NID
    #[serde(rename = "connection_nid")]
    pub connection_nid: String,
    /// The hashed connection token
    #[serde(rename = "connection_token_hash")]
    pub connection_token_hash: String,
    /// The URL to return to after identification
    #[serde(rename = "return_to")]
    pub return_to: String,
    /// A unique ID representing the member in the subscriber's backend
    #[serde(rename = "linking_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub linking_token: Option<Option<String>>,
}

impl IdentifyRequestBody {
    /// Request body for identification URL setup
    pub fn new(connection_nid: String, connection_token_hash: String, return_to: String) -> IdentifyRequestBody {
        IdentifyRequestBody {
            connection_nid,
            connection_token_hash,
            return_to,
            linking_token: None,
        }
    }
}

