/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdentifierObject : An identifier record
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifierObject {
    /// Database ID of the identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The UUID identifier
    #[serde(rename = "identifier", skip_serializing_if = "Option::is_none")]
    pub identifier: Option<uuid::Uuid>,
    /// The parent identifier UUID if this is a child
    #[serde(rename = "parent_uuid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent_uuid: Option<Option<uuid::Uuid>>,
    /// The type of identifier
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Creation timestamp
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
}

impl IdentifierObject {
    /// An identifier record
    pub fn new() -> IdentifierObject {
        IdentifierObject {
            id: None,
            identifier: None,
            parent_uuid: None,
            r#type: None,
            created: None,
        }
    }
}

