/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InviteStatusResponse : Response for checking invite status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteStatusResponse {
    /// Whether the invite exists
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<i32>,
    /// The status of the invite (pending, used, expired)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl InviteStatusResponse {
    /// Response for checking invite status
    pub fn new() -> InviteStatusResponse {
        InviteStatusResponse {
            success: None,
            status: None,
        }
    }
}

