/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InviteStatusRequestBody : Request body for checking invite status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteStatusRequestBody {
    /// The parent identifier
    #[serde(rename = "identifier")]
    pub identifier: uuid::Uuid,
    #[serde(rename = "app_url")]
    pub app_url: String,
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "con_nid")]
    pub con_nid: String,
    #[serde(rename = "org_id")]
    pub org_id: String,
    #[serde(rename = "project_id")]
    pub project_id: String,
    #[serde(rename = "item_id")]
    pub item_id: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl InviteStatusRequestBody {
    /// Request body for checking invite status
    pub fn new(identifier: uuid::Uuid, app_url: String, client_id: String, con_nid: String, org_id: String, project_id: String, item_id: String, r#type: String) -> InviteStatusRequestBody {
        InviteStatusRequestBody {
            identifier,
            app_url,
            client_id,
            con_nid,
            org_id,
            project_id,
            item_id,
            r#type,
        }
    }
}

