/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InviteRequestBody : Request body for storing and sending an identifier invite
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteRequestBody {
    /// The parent identifier
    #[serde(rename = "identifier")]
    pub identifier: uuid::Uuid,
    /// The application URL
    #[serde(rename = "app_url")]
    pub app_url: String,
    /// The OAuth2 client ID
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// The connection NID
    #[serde(rename = "con_nid")]
    pub con_nid: String,
    /// The organization ID
    #[serde(rename = "org_id")]
    pub org_id: String,
    /// The project ID
    #[serde(rename = "project_id")]
    pub project_id: String,
    /// The item ID
    #[serde(rename = "item_id")]
    pub item_id: String,
    /// The type of invitation
    #[serde(rename = "type")]
    pub r#type: String,
    /// Email message content
    #[serde(rename = "message_email")]
    pub message_email: String,
    /// SMS message content
    #[serde(rename = "message_sms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message_sms: Option<Option<String>>,
}

impl InviteRequestBody {
    /// Request body for storing and sending an identifier invite
    pub fn new(identifier: uuid::Uuid, app_url: String, client_id: String, con_nid: String, org_id: String, project_id: String, item_id: String, r#type: String, message_email: String) -> InviteRequestBody {
        InviteRequestBody {
            identifier,
            app_url,
            client_id,
            con_nid,
            org_id,
            project_id,
            item_id,
            r#type,
            message_email,
            message_sms: None,
        }
    }
}

