/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotifyMemberRequestBody : Request body for sending a notification to a member
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotifyMemberRequestBody {
    #[serde(rename = "identifier_auth")]
    pub identifier_auth: Box<models::IdentifierAuthObject>,
    /// Email message content
    #[serde(rename = "message_email")]
    pub message_email: String,
    /// SMS message content
    #[serde(rename = "message_sms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message_sms: Option<Option<String>>,
}

impl NotifyMemberRequestBody {
    /// Request body for sending a notification to a member
    pub fn new(identifier_auth: models::IdentifierAuthObject, message_email: String) -> NotifyMemberRequestBody {
        NotifyMemberRequestBody {
            identifier_auth: Box::new(identifier_auth),
            message_email,
            message_sms: None,
        }
    }
}

