/*
 * IDaaS API
 *
 * Identity as a Service API for member authentication, identifiers, and account management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateNotificationStatusRequestBody : Request body for updating notification status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateNotificationStatusRequestBody {
    /// The notification identifier to update
    #[serde(rename = "identifier")]
    pub identifier: uuid::Uuid,
}

impl UpdateNotificationStatusRequestBody {
    /// Request body for updating notification status
    pub fn new(identifier: uuid::Uuid) -> UpdateNotificationStatusRequestBody {
        UpdateNotificationStatusRequestBody {
            identifier,
        }
    }
}

